config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :missions, only: :index

  get "/scan", to: "pages#scan"
  get "/admin", to: "pages#admin"
  post "add_missions_to_users", to: "pages#add_missions_to_users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bungalow.rb
class Bungalow < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :missions, dependent: :destroy
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :challenge
  belongs_to :user
  belongs_to :target_user, class_name: "User", foreign_key: "target_user_id"
  belongs_to :winner_user, class_name: "User", foreign_key: "winner_user_id", optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :missions, dependent: :destroy
  belongs_to :bungalow, optional: true
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :telegram_user, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :telegram_user, :photo])
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @missions = current_user.missions
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :admin]

  def home
  end

  def admin
  end

  def add_missions_to_users
    Mission.destroy_all
    target_user = User.all.sample
    User.all.each do |user|
      while Mission.all.any? { |mission| mission.target_user == target_user }
        target_user = User.where.not(id: user.id).sample
      end
      Mission.create(user: user, challenge: Challenge.all.sample, target_user: target_user, status: "pending")
    end
    redirect_to admin_path
  end

  def scan
    @user_mission = current_user.missions.last
    @other_mission = Mission.where(challenge: @user_mission.challenge, target_user: @user_mission.target_user).where.not(user: current_user).last if @user_mission

    if current_user.qr.nil?
      current_user.update(qr: params[:qr])

    elsif current_user.qr == params[:qr]
      @mensaje = "Ya has registrado tu propio QR. 😒"

    elsif current_user.qr != params[:qr] && params[:qr].present?

      @user = User.find_by(qr: params[:qr])

      if @user.nil?
        @mensaje = "El QR que has escaneado no está asociado a ningún usuario. 😒"

      elsif current_user.missions.none? { |mission| mission.target_user.qr == params[:qr] }
        @mensaje = "Esta misión no te toca. 😒"

      elsif current_user.missions.any? { |mission| mission.target_user.qr == params[:qr] && mission.status == "completed" }
        @mensaje = "Ya has ganado esta misión. 😒"

      elsif @other_mission.present? && @other_mission.status == "completed"
        @mensaje = "Que has perdido ya. Deja de molestar. 😒"

      else
        current_user.missions.last.update(status: "completed", winner_user: current_user)
        @mensaje = "Has completado la misión. 🎉"

        @mission = Mission.find_by(user: @user)
        @new_mission = @mission.dup
        @new_mission.update(user: current_user)

        # TODO: Encontrar las misiones con el mismo target user y ponerlas con status completed
        # Ésta debería ser mi gran misión.
        Mission.where(target_user: @mission.target_user).update_all(status: "completed", winner_user: current_user)
        # Comprobar que la línea de arriba funciona correctamente.
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Lotus Game</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/missions/index.html.erb
<% @missions.each do |mission| %>
<p>
  <%= mission.challenge.description %>
</p>
<% end %>

app/views/pages/admin.html.erb
<%= button_to "Añadir Misiones A Usuarios", add_missions_to_users_path, method: :post %>
<br>
<h1>Misiones (total: <%= Mission.count %>)</h1>
<% Mission.all.each_with_index do |mission, index| %>
  <p><%= index + 1 %>. Misión de <strong><%= mission.user.first_name %> <%= mission.user.last_name %></strong> hacia <strong><%= mission.target_user.first_name %> <%= mission.target_user.last_name %></strong>.</p>
  <% if mission.user == mission.target_user %>
    <p style="color: red"><strong>¡Misión suicida!</strong></p>
 <% end %>
  <hr>
<% end %>
<h1>Usuarios (total: <%= User.count %>)</h1>
<% User.all.each_with_index do |user, index| %>
  <p><%= index + 1 %>. <%= user.first_name %> <%= user.last_name %> (<%= user.email %>). <span style="color: red"><%= "No tiene QR!" unless user.qr %></span></p>
<% end %>

app/views/pages/scan.html.erb
<h2 class="mt-3 fancy-font hot-title centered-text mb-3">Hola <%= current_user.first_name %>!</h2>
<% if current_user.photo.attached? %>
  <%= cl_image_tag @current_user.photo.key, class: "current-user-photo text-center" %>
  <div class="container">
    <p style="font-size: 12px"><em>Cuida tu collar, reina. Si ves a alguien acercándose con su móvil a tu cuello, es
        para
        robarte tu misión. No le dejes!</em></p>
  </div>
<% end %>
<% if @mensaje %>
  <div class="alert alert-primary" role="alert">
    <%= @mensaje %>
  </div>
<% end %>
<% if @other_mission.present? && @other_mission.status == "completed" %>
  <h2 style="color: red" class="mt-5 fancy-font hot-title centered-text mb-5">¡Cari! ¡Has perdido!</h2>
  <p>Tu rival te ha ganado y ha escaneado la que era tu misión. Ya no tienes nada que hacer. 😔</p>
  <p>Esperamos que hayas disfrutado del juego. Lo hemos hecho con mucho amor. ❤️</p>
  <p>¡Nos vemos en la fiesta!</p>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <br>
<% elsif @new_mission && @user_mission.present? %>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <h2 class="mt-3 fancy-font hot-title centered-text mb-3">¡Tienes una nueva misión!</h2>
  <% challenge = @new_mission.challenge.description %>
  <% full_name = @new_mission.target_user.first_name + " " + @new_mission.target_user.last_name %>
  <% challenge.gsub!("target", full_name) %>
  <div class="d-flex flex-row">
    <div class="p-2">
      <p><em><%= challenge %></em> </p>
    </div>
    <div class="p-2">
      <%= cl_image_tag @new_mission.target_user.photo.key, class: "target-user-photo" %>
    </div>
  </div>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <br>
  <h3 class="hot-title mb-3">Todas mis misiones:</h3>
  <div class="container">
    <% current_user.missions.each_with_index do |mission, index| %>
      <% the_name = mission.target_user.first_name + " " + mission.target_user.last_name %>
      <div class="d-flex flex-row">
        <div class="p-2">
          <p><%= index + 1 %>. <i><%= mission.challenge.description.gsub("target", the_name) %></i></p>
          <p>Estado: <strong><%= mission.status == "pending" ? "Pendiente" : "Ganada" %></strong></p>
        </div>
        <div class="p-2">
          <%= cl_image_tag mission.target_user.photo.key, class: "target-user-photo" %>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
<% elsif @user_mission.present? %>
  <% challenge = current_user.missions.last.challenge.description %>
  <% full_name = current_user.missions.last.target_user.first_name + " " + current_user.missions.last.target_user.last_name %>
  <% challenge.gsub!("target", full_name) %>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <br>
  <h3 class="text-center hot-title">Tu misión actual es:</h3>
  <div class="d-flex flex-row">
    <div class="p-2">
      <p><em><%= challenge %></em> </p>
    </div>
    <div class="p-2">
      <%= cl_image_tag current_user.missions.last.target_user.photo.key, class: "target-user-photo" %>
    </div>
  </div>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <br>
  <h3 class="hot-title mb-3">Todas mis misiones:</h3>
  <div class="container">
    <% current_user.missions.each_with_index do |mission, index| %>
      <% the_name = mission.target_user.first_name + " " + mission.target_user.last_name %>
      <div class="d-flex flex-row">
        <div class="p-2">
          <p><%= index + 1 %>. <i><%= mission.challenge.description.gsub("target", the_name) %></i></p>
          <p>Estado: <strong><%= mission.status == "pending" ? "Pendiente" : "Ganada" %></strong></p>
        </div>
        <div class="p-2">
          <%= cl_image_tag mission.target_user.photo.key, class: "target-user-photo" %>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
<% else %>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
  <br>
  <h4>Todavía no hay ninguna misión. A la noche del viernes, cuando todas nuestras huéspedes se hayan registrado... te
    tocará tu
    misión. 😱🔫</h4>
  <br>
  <hr style="border: 2px solid hotpink; width: 80vw; margin: auto;">
<% end %>
<br>
<h1 class="text-center">🪷🪷🪷</h1>
<br>
<hr style="border: 1px solid hotpink; width: 95vw; margin: auto;">
<%= link_to "Editar Perfil", edit_user_registration_path %>
<br>
<%= link_to "Tancar Sessió", destroy_user_session_path, data: {turbo_method: :delete} %>
<br>
<hr style="border: 1px solid hotpink; width: 95vw; margin: auto;">
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- ======= Footer ======= -->
<footer id="footer">
  <div class="footer-newsletter">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h4>Join Our Newsletter</h4>
          <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          <form action="" method="post">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 footer-contact">
          <h3>Arsha</h3>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br>
            <br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>
        </div>
        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Social Networks</h4>
          <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
          <div class="social-links mt-3">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container footer-bottom clearfix">
    <div class="copyright">
      &copy; Copyright <strong><span>Arsha</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </div>
</footer>
<!-- End Footer -->

app/views/shared/_navbar.html.erb
<header id="header" class="fixed-top ">
  <div class="container d-flex align-items-center">
    <a class="logo me-auto"><%= image_tag("logo", class: "img-fluid") %></a>
    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
        <li><a class="nav-link scrollto" href="#about">About</a></li>
        <li><a class="nav-link scrollto" href="#services">Services</a></li>
        <li><a class="nav-link scrollto" href="#team">Team</a></li>
        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        <li><a class="getstarted scrollto" href="#about">Get Started</a></li>
      </ul>
      <i class="fa-solid fa-bars fa-2xl mobile-nav-toggle" style="color: #f18da2;"></i>
    </nav>
  </div>
</header>